meta_product_name: "plana"
meta_title: "plana - live sustainable"
meta_description: "Hey I just found out my CO2 impact using plana, what's your? I bet I have a higher plana score than you 😉! Check it out, join plana!"
meta_image: "plana-og.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
