meta_product_name: "plana"
meta_title: "plana - live more sustainably"
meta_description: "Your guide to healthier habits, for you & for the planet."
meta_image: "plana-og.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
